---
abstract: 'repositor.io is a tool to create and manage linux repositories.'
author:
  - 'Jan Gehring <jfried@rexify.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rex-Repositorio
requires:
  Carp: '0'
  Compress::Zlib: '0'
  Config::General: '0'
  Data::Dumper: '0'
  Digest::MD5: '0'
  Digest::SHA: '0'
  Encode: '0'
  English: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  FindBin: '0'
  Getopt::Long: '0'
  IO::All: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  Log::Log4perl: '0'
  MIME::Base64: '0'
  Mojo::Base: '0'
  Mojo::Util: '0'
  Mojolicious::Commands: '0'
  Moose: '0'
  Params::Validate: '0'
  Term::ReadKey: '0'
  Try::Tiny: '0'
  XML::LibXML: '0'
  XML::Simple: '0'
  common::sense: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/RexOps/repositorio/issues
  homepage: http://www.repositor.io
  repository: https://github.com/RexOps/repositorio.git
version: 0.4.0
