---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rex-Repositorio
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Zlib: '0'
  Config::General: '0'
  File::Basename: '0'
  File::Path: '0'
  IO::All: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  Log::Log4perl: '0'
  Mojolicious: '0'
  Moose: '0'
  Params::Validate: '0'
  Term::ReadKey: '0'
  Try::Tiny: '0'
  XML::LibXML: '0'
  XML::Simple: '0'
  common::sense: '0'
resources:
  repository: https://github.com/krimdomu/repositorio
version: v0.3.0
